#!/usr/bin/env bash
# Wizard: walks a human through the clicks only a human can make, and records
# the results in the domain's connections.md. Generated by the jorekai-seo:connect skill.
#
# Everything above the STAGES marker is the library; author stages below it.
# Re-runnable: values already recorded are offered as defaults.
set -euo pipefail

CONNECTIONS="${CONNECTIONS:-docs/seo/DOMAIN/connections.md}"   # the agent sets this path
TOTAL_STAGES=0
_STAGE=0
WRITTEN=()
SKIPPED=()

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  B=$(tput bold); D=$(tput dim); R=$(tput sgr0); BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3)
else
  B=""; D=""; R=""; BLUE=""; GREEN=""; YELLOW=""
fi

_clear() { [[ -t 1 ]] || return 0; if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[H'; fi; }
say()   { printf '  %s\n' "$1"; }
step()  { printf '  %s•%s %s\n' "$BLUE" "$R" "$1"; }
note()  { printf '  %s%s%s\n' "$D" "$1" "$R"; }
warn()  { printf '  %s! %s%s\n' "$YELLOW" "$1" "$R"; }

banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$B" "$BLUE" "$1" "$R"
  printf '%s  %s stages. Records go to %s. Ctrl-C any time; re-run to continue.%s\n\n' "$D" "$TOTAL_STAGES" "$CONNECTIONS" "$R"
  pause "Press Enter to start"
}

stage() {
  _clear
  _STAGE=$((_STAGE + 1))
  printf '\n%s%s> Stage %s/%s: %s%s\n' "$B" "$BLUE" "$_STAGE" "$TOTAL_STAGES" "$1" "$R"
}

open_url() {
  printf '  %sopening%s %s\n' "$GREEN" "$R" "$1"
  { if   command -v wslview >/dev/null 2>&1; then wslview "$1"
    elif command -v xdg-open >/dev/null 2>&1; then xdg-open "$1"
    elif command -v open >/dev/null 2>&1; then open "$1"
    else warn "open it yourself: $1"; fi
  } >/dev/null 2>&1 || warn "open it yourself: $1"
}

pause()   { printf '  %s%s%s ' "$D" "${1:-Press Enter to continue}" "$R"; read -r _ || true; }
confirm() { local a=""; printf '  %s? %s [y/N] ' "$YELLOW" "$1"; read -r a || true; [[ "$a" =~ ^[Yy] ]]; }

# current KEY: the value recorded for KEY, if any.
current() {
  [[ -f "$CONNECTIONS" ]] || return 1
  local line; line=$(grep -E "^- ${1}:" "$CONNECTIONS" | tail -n1) || return 1
  line="${line#*: }"; [[ "$line" == "- ${1}:" ]] && return 1
  [[ "$line" =~ ^\( ]] && return 1     # still the template placeholder
  printf '%s' "$line"
}

# ask KEY "Prompt": read a value into $KEY; Enter keeps the recorded value.
ask() {
  local key="$1" prompt="$2" cur input
  cur=$(current "$key" || true)
  if [[ -n "$cur" ]]; then printf '  %s%s%s %s[Enter keeps: %s]%s ' "$B" "$prompt" "$R" "$D" "$cur" "$R"
  else printf '  %s%s%s ' "$B" "$prompt" "$R"; fi
  read -r input || true
  [[ -z "$input" && -n "$cur" ]] && input="$cur"
  printf -v "$key" '%s' "$input"
}

# record KEY VALUE: upsert "- KEY: VALUE" in CONNECTIONS.
record() {
  local key="$1" value="$2" tmp
  [[ -f "$CONNECTIONS" ]] || { mkdir -p "$(dirname "$CONNECTIONS")"; printf '# connections\n\n' > "$CONNECTIONS"; }
  tmp=$(mktemp)
  if grep -qE "^- ${key}:" "$CONNECTIONS"; then
    awk -v k="$key" -v v="$value" 'index($0, "- " k ":") == 1 { print "- " k ": " v; next } { print }' "$CONNECTIONS" > "$tmp"
  else
    cat "$CONNECTIONS" > "$tmp"; printf -- '- %s: %s\n' "$key" "$value" >> "$tmp"
  fi
  mv "$tmp" "$CONNECTIONS"
  WRITTEN+=("$key")
  printf '  %srecorded%s %s: %s\n' "$GREEN" "$R" "$key" "$value"
}

skip() { SKIPPED+=("$1"); warn "left for later: $1"; }
today() { date +%F; }

# http_status URL: the HTTP status code, or 000 when unreachable.
http_status() { curl -s -o /dev/null -w '%{http_code}' -A "jorekai-seo:connect wizard" --max-time 15 "$1" || printf '000'; }

finish() {
  _clear
  printf '\n%s%s  Done%s\n' "$B" "$GREEN" "$R"
  (( ${#WRITTEN[@]} )) && note "recorded ${#WRITTEN[@]} value(s) in $CONNECTIONS: ${WRITTEN[*]}"
  if (( ${#SKIPPED[@]} )); then printf '\n'; warn "still to do by hand:"; for s in "${SKIPPED[@]}"; do note "  - $s"; done; fi
  printf '\n'
}

